#!/usr/bin/env node

/**
 * Script to switch back to mock data for development
 * Usage: node scripts/switch-to-mock.js
 */

import fs from 'fs';
import path from 'path';

console.log('🔄 Switching back to mock data...');

// Update .env file to use mock data
const envContent = `# Algeria Eats Hub - Environment Configuration
# Generated by switch-to-mock.js

# API Configuration
VITE_API_BASE_URL=http://localhost:8080/api
VITE_USE_MOCK_DATA=true

# Development Settings
VITE_DEBUG_MODE=true
VITE_LOG_LEVEL=info

# File Upload
VITE_UPLOAD_MAX_SIZE=5242880
VITE_UPLOAD_ALLOWED_TYPES=image/jpeg,image/png,image/gif,image/webp
`;

try {
  fs.writeFileSync('.env', envContent);
  console.log('✅ Updated .env file to use mock data');
} catch (error) {
  console.error('❌ Failed to update .env file:', error.message);
}

// Update mockData.ts to force mock data
const mockDataPath = path.join('src', 'api', 'mockData.ts');

try {
  let mockDataContent = fs.readFileSync(mockDataPath, 'utf8');
  
  // Replace the shouldUseMockData function
  const oldFunction = /export const shouldUseMockData = \(\): boolean => \{[\s\S]*?\};/;
  const newFunction = `export const shouldUseMockData = (): boolean => {
  // Force mock data for development
  return true;
};`;

  if (oldFunction.test(mockDataContent)) {
    mockDataContent = mockDataContent.replace(oldFunction, newFunction);
    fs.writeFileSync(mockDataPath, mockDataContent);
    console.log('✅ Updated mockData.ts to force mock data');
  } else {
    console.log('⚠️  Could not find shouldUseMockData function to update');
  }
} catch (error) {
  console.error('❌ Failed to update mockData.ts:', error.message);
}

console.log('\n🎉 Mock data switch completed!');
console.log('\nYou can now develop with mock data.');
console.log('Start development: npm run dev');

console.log('\nTo switch back to real backend:');
console.log('node scripts/switch-to-backend.js [backend-url]');
